# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 2
newline_style = "Auto"
reorder_imports = true
reorder_modules = true
use_try_shorthand = true
use_field_init_shorthand = true
remove_nested_parens = true
force_explicit_abi = true
